#ifndef COMPLEMENTARY_FILTER_ROS2__VISIBILITY_CONTROL_H_
#define COMPLEMENTARY_FILTER_ROS2__VISIBILITY_CONTROL_H_
#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define COMPLEMENTARY_FILTER_ROS2_EXPORT __attribute__ ((dllexport))
    #define COMPLEMENTARY_FILTER_ROS2_IMPORT __attribute__ ((dllimport))
  #else
    #define COMPLEMENTARY_FILTER_ROS2_EXPORT __declspec(dllexport)
    #define COMPLEMENTARY_FILTER_ROS2_IMPORT __declspec(dllimport)
  #endif
  #ifdef COMPLEMENTARY_FILTER_ROS2_BUILDING_LIBRARY
    #define COMPLEMENTARY_FILTER_ROS2_PUBLIC COMPLEMENTARY_FILTER_ROS2_EXPORT
  #else
    #define COMPLEMENTARY_FILTER_ROS2_PUBLIC COMPLEMENTARY_FILTER_ROS2_IMPORT
  #endif
  #define COMPLEMENTARY_FILTER_ROS2_PUBLIC_TYPE COMPLEMENTARY_FILTER_ROS2_PUBLIC
  #define COMPLEMENTARY_FILTER_ROS2_LOCAL
#else
  #define COMPLEMENTARY_FILTER_ROS2_EXPORT __attribute__ ((visibility("default")))
  #define COMPLEMENTARY_FILTER_ROS2_IMPORT
  #if __GNUC__ >= 4
    #define COMPLEMENTARY_FILTER_ROS2_PUBLIC __attribute__ ((visibility("default")))
    #define COMPLEMENTARY_FILTER_ROS2_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define COMPLEMENTARY_FILTER_ROS2_PUBLIC
    #define COMPLEMENTARY_FILTER_ROS2_LOCAL
  #endif
  #define COMPLEMENTARY_FILTER_ROS2_PUBLIC_TYPE
#endif
#endif  // COMPLEMENTARY_FILTER_ROS2__VISIBILITY_CONTROL_H_
// Generated 17-Jun-2024 12:49:23
 